services:

  postgres:
    image: postgres:16
    container_name: shecancode-postgres

    environment:
      POSTGRES_DB: shecancode
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: shecancode-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@shecancode.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - postgres

  app:
    build: .
    container_name: shecancode-app

    depends_on:
      - postgres

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shecancode
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      JWT_SECRET: my-super-secret-jwt-key-for-shecancode-attendance-system-256bits

    ports:
      - "8080:8080"

volumes:
  postgres_data:

